# Generated by Django 5.2.1 on 2025-06-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Identifiant de transaction')),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20, verbose_name='Statut du paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé')),
                ('currency', models.CharField(default='XAF', max_length=10, verbose_name='Devise')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('payer_name', models.CharField(max_length=255, verbose_name='Nom du payeur')),
                ('payer_account', models.CharField(max_length=100, verbose_name='Compte/ID du payeur')),
                ('payment_method', models.CharField(choices=[('card', 'Carte'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement Bancaire'), ('cash', 'Paiement Cash')], max_length=20, verbose_name='Méthode de paiement')),
                ('bank_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence bancaire')),
                ('confirmation_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code de confirmation')),
                ('order_id', models.CharField(max_length=100, verbose_name='Identifiant de commande')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frais appliqués')),
                ('signature', models.CharField(max_length=255, verbose_name='Signature numérique')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
        ),
    ]
