# Generated by Django 5.2.1 on 2025-06-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='motard_matricule',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='ID Motard'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', max_length=10, verbose_name='Devise'),
        ),
    ]
