# Generated by Django 5.2.1 on 2025-06-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_motard_matricule_alter_payment_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Transaction de Formation'},
        ),
    ]
