# Generated by Django 5.2.1 on 2025-07-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Frais appliqués'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Identifiant de commande'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte'), ('mobile', 'Mobile Money'), ('bank', 'Virement Bancaire'), ('cash', 'Paiement Cash')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='signature',
            field=models.CharField(max_length=255, null=True, verbose_name='Signature numérique'),
        ),
    ]
