# Generated by Django 5.2.1 on 2025-07-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_fee_alter_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='motard_matricule',
            field=models.CharField(max_length=100, null=True, verbose_name='ID Motard'),
        ),
    ]
