# Generated by Django 5.2.1 on 2025-07-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_motard_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Montant')),
                ('actif', models.BooleanField(default=False, verbose_name='Montant Actif')),
            ],
            options={
                'verbose_name': 'Montant',
                'verbose_name_plural': 'Montants',
            },
        ),
    ]
