# Generated by Django 5.2.1 on 2025-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='montant',
            name='taux',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taux du jour'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='motard_matricule',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='ID Motard'),
        ),
    ]
