# Generated by Django 5.2.1 on 2025-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_montant_taux_alter_payment_motard_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montant',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='montant',
            name='taux',
        ),
        migrations.AddField(
            model_name='montant',
            name='montant_cdf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Montant en CDF'),
        ),
        migrations.AddField(
            model_name='montant',
            name='montant_usd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Montant en USD'),
        ),
    ]
