# Generated by Django 5.2.1 on 2025-05-30 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moto',
            options={'verbose_name': 'Moto', 'verbose_name_plural': 'Motos'},
        ),
        migrations.AlterField(
            model_name='moto',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='chassis_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Numéro de châssis'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='moto',
            name='image_moto',
            field=models.ImageField(upload_to='motos/', verbose_name='Photo de la moto'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='plate_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de plaque'),
        ),
    ]
