# Generated by Django 5.2.1 on 2025-05-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_alter_moto_options_alter_moto_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='image_moto',
            field=models.ImageField(upload_to='static/motos/', verbose_name='Photo de la moto'),
        ),
    ]
