# Generated by Django 5.2.1 on 2025-05-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0003_alter_moto_image_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='image_moto',
            field=models.ImageField(upload_to='static/motos/%Y/', verbose_name='Photo de la moto'),
        ),
    ]
