# Generated by Django 5.2.1 on 2025-05-31 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0005_alter_moto_image_moto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moto',
            old_name='image_moto',
            new_name='image',
        ),
    ]
