# Generated by Django 5.2.1 on 2025-05-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0006_rename_image_moto_moto_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moto',
            options={},
        ),
    ]
