# Generated by Django 5.2.1 on 2025-05-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0007_alter_moto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moto',
            options={'verbose_name': 'Moto', 'verbose_name_plural': 'Motos'},
        ),
    ]
