# Generated by Django 5.2.1 on 2025-06-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0009_alter_moto_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moto',
            options={'verbose_name': 'Moto', 'verbose_name_plural': 'Motos Identifiées'},
        ),
    ]
