# Generated by Django 5.2.1 on 2025-05-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_motard_photo_identite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motard',
            name='photo_identite',
            field=models.ImageField(blank=True, null=True, upload_to='static/photos_identite/%Y/', verbose_name="Photo d'identité récente"),
        ),
        migrations.AlterField(
            model_name='motard',
            name='piece_identite',
            field=models.ImageField(blank=True, null=True, upload_to='static/pieces_identite/%Y/', verbose_name="Scan/Photo de pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='motard',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='static/profiles/%Y/', verbose_name='Photo de profil'),
        ),
    ]
