# Generated by Django 5.2.1 on 2025-06-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_motard_photo_identite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motard',
            name='piece_identite',
        ),
        migrations.AddField(
            model_name='motard',
            name='autre_piece',
            field=models.ImageField(blank=True, null=True, upload_to='pieces_identite/%Y/', verbose_name='Autre pièce'),
        ),
    ]
