# Generated by Django 5.2.1 on 2025-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_motard_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motard',
            name='matricule',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Matricule'),
        ),
    ]
