# Generated by Django 5.2.1 on 2025-06-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_motard_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='motard',
            name='type_user',
            field=models.CharField(choices=[('motard', 'Motard'), ('motosekur', 'Moto Sekur'), ('autre', 'Autre')], default='motard', max_length=20, verbose_name="Type d'utilisateur"),
        ),
    ]
