# Generated by Django 5.2.1 on 2025-08-27 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_motard_type_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_usd', models.CharField(blank=True, max_length=100, null=True, verbose_name='Montant en USD')),
                ('montant_cdf', models.CharField(blank=True, max_length=100, null=True, verbose_name='Montant en CDF')),
                ('actif', models.BooleanField(default=False, verbose_name='Montant Actif')),
            ],
            options={
                'verbose_name': 'Montant',
                'verbose_name_plural': 'Montants',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(default='Education', max_length=100)),
                ('coverImage', models.ImageField(upload_to='videos/covers/')),
                ('video', models.FileField(upload_to='videos/files/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='motos/%Y/', verbose_name='Photo de la moto')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('plate_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de plaque')),
                ('chassis_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de châssis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos Identifiées',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motard_matricule', models.CharField(max_length=100, null=True, unique=True, verbose_name='ID Motard')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Identifiant de transaction')),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20, verbose_name='Statut du paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Devise')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('payer_name', models.CharField(max_length=255, verbose_name='Nom du payeur')),
                ('payer_account', models.CharField(max_length=100, verbose_name='Compte/ID du payeur')),
                ('payment_method', models.CharField(choices=[('card', 'Carte'), ('mobile', 'Mobile Money'), ('bank', 'Virement Bancaire'), ('cash', 'Paiement Cash')], max_length=20, verbose_name='Méthode de paiement')),
                ('bank_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence bancaire')),
                ('confirmation_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Code de confirmation')),
                ('order_id', models.CharField(max_length=100, null=True, verbose_name='Identifiant de commande')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Frais appliqués')),
                ('signature', models.CharField(max_length=255, null=True, verbose_name='Signature numérique')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Transaction de Formation',
            },
        ),
    ]
