# Generated by Django 5.2.1 on 2025-08-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_montant_video_moto_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='coverImage',
            new_name='cover_image',
        ),
    ]
